### ISSUE TITLE
I am unable to run this.  

### ISSUE THREAD

**Issue by muttequrashi** [DIAGNijmegen/picai_baseline#15]
Traceback (most recent call last):
  File "train.py", line 165, in <module>
    main()
  File "train.py", line 140, in main
    args=args, tracking_metrics=tracking_metrics, device=device, writer=writer
  File "/cs/research/external/home/namjad/Downloads/picai_baseline/src/picai_baseline/unet/training_setup/callbacks.py", line 117, in optimize_model
    loss = loss_func(outputs, labels[:,0, ...].long())
  File "/cs/research/external/home/namjad/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/cs/research/external/home/namjad/Downloads/picai_baseline/src/picai_baseline/unet/training_setup/loss_functions/focal.py", line 32, in forward
    targets = F.one_hot(targets, num_classes=self.num_classes).float()
RuntimeError: CUDA error: device-side assert triggered
88 namjad@blaze% python3 -u train.py --weights_dir='/cs/research/external/home/namjad/Downloads/picai_baseline/src/picai_baseline/workdir/results/UNet/weights/' --overviews_dir='/cs/research/external/home/namjad/Downloads/picai_baseline/src/picai_baseline/workdir/results/UNet/overviews/' --folds 1 --max_threads 6 --enable_da 1 --num_epochs 250 --validate_n_epochs 1 --validate_min_epoch 0 --num_classes 5

**Comment by joeranbosma** [comment]
Hi @muttequrashi,

The error you face (’RuntimeError: CUDA error: device-side assert triggered’) appears to be caused by an “Inconsistency between the number of labels/classes and the number of output units” (according to https://builtin.com/software-engineering-perspectives/cuda-error-device-side-assert-triggered). 

Your training command specifies ‘--num_classes 5’, which is different from our [baseline](https://github.com/DIAGNijmegen/picai_baseline/blob/main/src/picai_baseline/unet/train.py) (we use binarized labels, and therefore have 2 classes). 
Did you change this on purpose? If not, change this to ‘2’. If so, I think your issue lies there. If you want to train with five classes, make sure the data loader prepares the labels correctly. For example, you can print the shape of the labels before you calculate the loss, to see if the dimensions are correct. Also, please be aware of the [label mapping](https://github.com/DIAGNijmegen/picai_labels#label-mapping-of-cspca-annotations) when combining human and AI-derived annotations. 

Hope this helps,
Joeran

**Comment by muttequrashi** [comment]
I tried with that also but then it's a different error. Because in the code you are checking for a unique number of classes which are 5 I checked that also that's why I used 5. But it doesn't work with 2 also. Plus setting up the directories is super confusing maybe you can have some bash scripts according to your structure to set up the directories stuff as python normally don't have sudo permissions on Linux to make directories.

**Comment by joeranbosma** [comment]
Hi @muttequrashi,

Apologies for the late response, I was on holiday.

I'm afraid I'm not following you. Where in the code does it check and determine that the number of classes is five? Although the [original labels have five possible values](https://github.com/DIAGNijmegen/picai_labels#label-mapping-of-cspca-annotations), each of the baseline algorithms transform these annotations to a binary setup with background (0) and csPCa (1). The number of classes during training is therefore 2 for the baseline algorithms (because one-hot encoding with softmax is used, not sigmoid).

What error did you observe when running with two classes? This may indicate that the previous issue is resolved by changing it to two, but that you are running into the next/another issue.

We have an overview of the required folders here: https://github.com/DIAGNijmegen/picai_baseline#folder-structure. Depending on the algorithm (nnU-Net/nnDetection/UNet) more folders are required, which will be created on the fly. If you set up permissions correctly, this should not be an issue.

We highly recommend you follow the [steps for one of the baseline solutions](https://github.com/DIAGNijmegen/picai_baseline/), without skipping anything, before adapting the codebase to do different things.
